version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hdoc-backend-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eqs40sdgkcq6"
s3_prefix = "hdoc-backend-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "AppName=\"hdoc\" Stage=\"dev""

