version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HundredDaysOfCloudWebsite-CodePipeline-Dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eqs40sdgkcq6"
s3_prefix = "HundredDaysOfCloudWebsite-CodePipeline-Dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"HundredDaysOfCloudWebsite\" GithubRepo=\"/100DaysOfCloud/Backend/GithubRepo\" GithubToken=\"/100DaysOfCloud/Backend/GithubTokenS\" GithubUser=\"/100DaysOfCloud/Backend/GithubUser\""
