version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hdoc-backend-dev-codepipeline"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eqs40sdgkcq6"
s3_prefix = "hdoc-backend-dev-codepipeline"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"hdoc\" GithubRepo=\"/100DaysOfCloud/Backend/GithubRepo\" GithubToken=\"/100DaysOfCloud/Backend/GithubTokenS\" GithubUser=\"/100DaysOfCloud/Backend/GithubUser\""
