name: backend-ci

on:
  pull_request:
    branches: [ dev ]
    paths:
      - 'sam/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r sam/requirements.txt
      - name: Test with pytest
        run: pytest -vv
