name: Greeting
on:
  push:
    branches:
      - dev

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo something
        run: echo 'Bonjour *polar bear appears out of snow*'
